using System;
using Postgrest.Attributes;
using Postgrest.Models;

namespace SupabaseExampleXA.Models
{
    [Table("counters")]
    public class Counter : BaseModel
    {
        [PrimaryKey("id", true)] // Key is Autogenerated
        public int Id { get; set; }

        [Column("count")]
        public int Count { get; set; }

        [Column("updated_at")]
        public DateTime UpdatedAt { get; set; }
    }
}
